name: lark_auth_server
server_id: 1
log: "./configs/logger.yaml"
grpc_server:
  name: lark_auth_server
  server_id: 1
  port: 6600
  max_connection_idle: 0
  max_connection_age: 0
  max_connection_age_grace: 0
  time: 7200000
  timeout: 20000
  connection_limit: 2000
  streams_limit: 2000
  max_recv_msg_size: 4096
  credential:
    cert_file: ./configs/tls/grpc/server.pem
    key_file: ./configs/tls/grpc/server.key
    enabled: true
  jaeger:
    host_port: "127.0.0.1:6831"
    sampler_type: "const"
    param: 1
    log_spans: true
    buffer_flush_interval: 1
    max_packet_size: 0
    enabled: false
etcd:
  endpoints: ["127.0.0.1:2379"]
  username:
  password:
  schema: lark
  read_timeout: 5000
  write_timeout: 5000
  dial_timeout: 5000
mysql:
  address: ["127.0.0.1:3306"]
  username: root
  password: 123456
  db: lark_user
  max_open_conns: 20
  max_idle_conns: 10
  max_lifetime: 120000
  max_idle_time: 7200000
  charset: utf8
redis:
  address: ["127.0.0.1:6379"]
  db: 0
  password:
  prefix: "LK:"